const mongoose = require('mongoose');
const dotenv = require('dotenv');
const xlsx = require('xlsx');
const fs = require('fs');
const path = require('path');
const http = require('http');

dotenv.config();
const API_BASE = 'https://certiverify-backend.onrender.com/api';
const results = [];

function log(msg) { results.push(msg); console.log(msg); }

function createExcel(filename, rows) {
    const wb = xlsx.utils.book_new();
    const ws = xlsx.utils.json_to_sheet(rows);
    xlsx.utils.book_append_sheet(wb, ws, 'Sheet1');
    const fp = path.join(__dirname, filename);
    xlsx.writeFile(wb, fp);
    return fp;
}

function uploadExcelRaw(token, filePath) {
    return new Promise((resolve, reject) => {
        const boundary = '----Form' + Math.random().toString(36).slice(2);
        const fileData = fs.readFileSync(filePath);
        const prefix = Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="${path.basename(filePath)}"\r\nContent-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\r\n\r\n`);
        const suffix = Buffer.from(`\r\n--${boundary}--\r\n`);
        const body = Buffer.concat([prefix, fileData, suffix]);
        const url = new URL(`${API_BASE}/certificates/upload`);
        const req = http.request({ hostname: url.hostname, port: url.port, path: url.pathname, method: 'POST', headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}`, 'Content-Length': body.length, 'Authorization': `Bearer ${token}` } }, (res) => {
            let d = ''; res.on('data', c => d += c);
            res.on('end', () => { try { resolve({ status: res.statusCode, data: JSON.parse(d) }); } catch { resolve({ status: res.statusCode, data: { message: d } }); } });
        });
        req.on('error', reject); req.write(body); req.end();
    });
}

async function main() {
    log('== EXCEL UPLOAD TEST ==');
    await mongoose.connect(process.env.MONGO_URI);
    await mongoose.connection.db.collection('certificates').deleteMany({});
    log('DB cleared.');

    try { await fetch(`${API_BASE}/auth/register`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: 'Admin', email: 'xltest@t.com', password: 'pass1234', adminPasscode: 'admin123' }) }); } catch {}
    const lr = await fetch(`${API_BASE}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'xltest@t.com', password: 'pass1234' }) });
    const { token } = await lr.json();
    log('Token OK');

    // T1: With IDs
    log('\n-- T1: WITH IDs --');
    const f1 = createExcel('t1.xlsx', [
        { Name: 'Alice', CertificateID: 'M-001', Course: 'React', Date: '2026-04-01' },
        { Name: 'Bob', CertificateID: 'M-002', Course: 'Node', Date: '2026-04-02' },
        { Name: 'Charlie', CertificateID: 'M-003', Course: 'Mongo', Date: '2026-04-03' },
    ]);
    let r = await uploadExcelRaw(token, f1);
    log(`Status: ${r.status} | In:${r.data.summary?.inserted} Rej:${r.data.summary?.rejected} Auto:${r.data.summary?.autoGenerated}`);
    log(`T1 Upload: ${r.status===200 && r.data.summary?.inserted===3 ? 'PASS' : 'FAIL'}`);

    for (const id of ['M-001','M-002','M-003']) {
        const v = await (await fetch(`${API_BASE}/certificates/verify/${id}`, { headers: { 'Authorization': `Bearer ${token}` } })).json();
        log(`Verify ${id}: ${v.valid ? 'PASS' : 'FAIL'}`);
    }

    // T2: Without IDs
    log('\n-- T2: WITHOUT IDs --');
    const f2 = createExcel('t2.xlsx', [
        { Name: 'David', Course: 'ML', Date: '2026-04-04' },
        { Name: 'Eve', Course: 'DS', Date: '2026-04-05' },
        { Name: 'Frank', Course: 'DL', Date: '2026-04-06' },
    ]);
    r = await uploadExcelRaw(token, f2);
    log(`Status: ${r.status} | In:${r.data.summary?.inserted} Rej:${r.data.summary?.rejected} Auto:${r.data.summary?.autoGenerated}`);
    log(`T2 Upload: ${r.status===200 && r.data.summary?.autoGenerated===3 ? 'PASS' : 'FAIL'}`);
    log(`Msg: ${r.data.message}`);

    let list = await (await fetch(`${API_BASE}/certificates?page=1&limit=20`, { headers: { 'Authorization': `Bearer ${token}` } })).json();
    const autos = list.certificates.filter(c => c.certId.match(/^CERT-\d{4}-\d{4}$/));
    log(`Auto format: ${autos.length===3 ? 'PASS' : 'FAIL'} (${autos.length})`);
    autos.forEach(c => log(`  ${c.certId} | ${c.name} | ${c.course}`));
    log(`Total: ${list.total===6 ? 'PASS' : 'FAIL'} (${list.total})`);

    // T3: Duplicates
    log('\n-- T3: DUPLICATES --');
    r = await uploadExcelRaw(token, f1);
    log(`Re-upload: In:${r.data.summary?.inserted} Rej:${r.data.summary?.rejected}`);
    log(`Dupe block: ${r.data.summary?.rejected===3 && r.data.summary?.inserted===0 ? 'PASS' : 'FAIL'}`);

    const f3 = createExcel('t3.xlsx', [
        { Name: 'Grace', Course: 'Compilers', Date: '2026-04-07' },
        { Name: 'Hank', Course: 'Quantum', Date: '2026-04-08' },
    ]);
    r = await uploadExcelRaw(token, f3);
    log(`New auto: In:${r.data.summary?.inserted} Auto:${r.data.summary?.autoGenerated}`);
    log(`Incr IDs: ${r.data.summary?.autoGenerated===2 ? 'PASS' : 'FAIL'}`);

    list = await (await fetch(`${API_BASE}/certificates?page=1&limit=20`, { headers: { 'Authorization': `Bearer ${token}` } })).json();
    const ids = list.certificates.map(c => c.certId);
    log(`Final: ${list.total===8 ? 'PASS' : 'FAIL'} (${list.total})`);
    log(`Unique: ${ids.length === new Set(ids).size ? 'PASS' : 'FAIL'}`);

    log('\n-- REGISTRY --');
    list.certificates.forEach(c => log(`${c.certId} | ${c.name} | ${c.course} | ${c.date}`));

    // T4: PDF
    log('\n-- T4: PDF --');
    const ac = list.certificates.find(c => c.certId.startsWith('CERT-'));
    if (ac) {
        const dl = await fetch(`${API_BASE}/certificates/download/${ac.certId}`, { headers: { 'Authorization': `Bearer ${token}` } });
        const buf = await dl.arrayBuffer();
        log(`PDF ${ac.certId}: ${dl.status===200 ? 'PASS' : 'FAIL'} (${buf.byteLength}b)`);
    }

    ['t1.xlsx','t2.xlsx','t3.xlsx'].forEach(f => { try { fs.unlinkSync(path.join(__dirname, f)); } catch {} });
    
    // Write results
    fs.writeFileSync(path.join(__dirname, 'test_output.log'), results.join('\n'), 'utf8');
    log('\nDone. Results in test_output.log');
    await mongoose.disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
