const Certificate = require('../models/Certificate');
const xlsx = require('xlsx');
const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');
const qrcode = require('qrcode');

// Helper function to generate unique certificate ID
// batchOffset accounts for IDs generated earlier in the same upload batch
const generateUniqueCertificateId = async (batchOffset = 0) => {
    const year = new Date().getFullYear();
    const prefix = `CERT-${year}-`;

    // Find the highest number for this year
    const lastCert = await Certificate.findOne(
        { certId: { $regex: `^${prefix.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}` } },
        { certId: 1 },
        { sort: { certId: -1 } }
    );

    let nextNumber = 1;
    if (lastCert) {
        const lastNumber = parseInt(lastCert.certId.split('-')[2]);
        nextNumber = lastNumber + 1;
    }

    nextNumber += batchOffset;

    return `${prefix}${String(nextNumber).padStart(4, '0')}`;
};

const uploadCertificates = async (req, res) => {
    try {
        if (!req.file) return res.status(400).json({ message: 'No file uploaded.' });

        const workbook = xlsx.readFile(req.file.path);
        const data = xlsx.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]]);

        if (data.length === 0) {
            return res.status(400).json({ message: 'Excel file is empty.' });
        }

        let inserted = 0;
        let rejected = 0;
        let autoGenerated = 0;

        let frontendUrl = req.get('origin') || process.env.FRONTEND_URL || 'https://certiverify-eight.vercel.app';
        if (frontendUrl && frontendUrl.endsWith('/')) {
            frontendUrl = frontendUrl.slice(0, -1);
        }

        // Helper: find a value from a row using multiple possible column names
        const getField = (row, possibleNames) => {
            for (const key of possibleNames) {
                // Check exact match first
                if (row[key] !== undefined && row[key] !== null && row[key] !== '') {
                    return row[key].toString().trim();
                }
            }
            // Check case-insensitive
            const rowKeys = Object.keys(row);
            for (const key of possibleNames) {
                const found = rowKeys.find(k => k.toLowerCase().replace(/[_\s]/g, '') === key.toLowerCase().replace(/[_\s]/g, ''));
                if (found && row[found] !== undefined && row[found] !== null && row[found] !== '') {
                    return row[found].toString().trim();
                }
            }
            return null;
        };

        for (let row of data) {
            // Flexible column name mapping
            const name = getField(row, ['Name', 'StudentName', 'Student Name', 'Student_Name', 'FullName', 'Full Name', 'Candidate', 'Candidate Name']);
            const course = getField(row, ['Course', 'Domain', 'DomainName', 'Domain Name', 'Domain_Name', 'Program', 'Subject', 'CourseName', 'Course Name']);
            const date = getField(row, ['Date', 'IssueDate', 'Issue Date', 'Issue_Date', 'IssuedDate', 'Issued Date', 'StartDate', 'Start Date', 'CompletionDate', 'Completion Date']);
            const certId = getField(row, ['CertificateID', 'Certificate ID', 'Certificate_ID', 'CertID', 'Cert ID', 'Cert_ID', 'CertId', 'ID', 'CertificateId', 'certificateId', 'certificateid']);

            // Reject only if critical data is missing (name and course are minimum required)
            if (!name || !course) {
                rejected++;
                continue;
            }

            try {
                let finalCertId = certId;

                // Auto-generate certificate ID if not provided
                if (!finalCertId) {
                    finalCertId = await generateUniqueCertificateId(autoGenerated);
                    autoGenerated++;
                } else {
                    // Check if provided ID already exists
                    const existing = await Certificate.findOne({ certId: finalCertId });
                    if (existing) {
                        rejected++;
                        continue;
                    }
                }

                const verifyUrl = `${frontendUrl}/verify?id=${finalCertId}`;
                const qrCodeData = await qrcode.toDataURL(verifyUrl);

                await Certificate.create({
                    name: name,
                    certId: finalCertId,
                    course: course,
                    date: date || new Date().toISOString().split('T')[0],  // Default to today if no date
                    qrCode: qrCodeData
                });
                inserted++;
            } catch (err) {
                // Handle duplicate key error gracefully
                rejected++;
            }
        }

        let message = "Uploaded successfully";
        if (autoGenerated > 0) {
            message += ` | Certificate IDs auto-generated for ${autoGenerated} missing entries`;
        }

        res.json({ message, summary: { inserted, rejected, autoGenerated } });
    } catch (err) {
        res.status(500).json({ message: "Server error", error: err.message });
    }
};

const createCertificate = async (req, res) => {
    try {
        const { name, studentName, certId, certificateId, course, domain, date, startDate, endDate } = req.body;

        // Handle flexible field names
        const finalName = name || studentName;
        const finalCertId = certId || certificateId;
        const finalCourse = course || domain;
        const finalDate = date || startDate || endDate;

        if (!finalName || !finalCertId || !finalCourse) {
            return res.status(400).json({ message: "Missing fields: name, certId, and course are required." });
        }

        const existing = await Certificate.findOne({ certId: finalCertId.trim() });
        if (existing) {
            return res.status(400).json({ message: "Certificate ID already exists" });
        }

        let frontendUrl = req.get('origin') || process.env.FRONTEND_URL || 'https://certiverify-eight.vercel.app';
        if (frontendUrl && frontendUrl.endsWith('/')) {
            frontendUrl = frontendUrl.slice(0, -1);
        }

        const verifyUrl = `${frontendUrl}/verify?id=${finalCertId.trim()}`;
        const qrCodeData = await qrcode.toDataURL(verifyUrl);

        const newCert = await Certificate.create({
            name: finalName,
            certId: finalCertId.trim(),
            course: finalCourse,
            date: finalDate,
            qrCode: qrCodeData
        });
        res.status(201).json(newCert);
    } catch (err) {
        if (err.code === 11000) {
            return res.status(400).json({ message: "Certificate ID already exists" });
        }
        res.status(400).json({ message: err.message });
    }
};

const getCertificates = async (req, res) => {
    try {
        const page = parseInt(req.query.page) || 1;
        const limit = parseInt(req.query.limit) || 10;
        const search = req.query.search || "";

        let query = {};
        if (search) {
            query = {
                $or: [
                    { name: { $regex: search, $options: "i" } },
                    { certId: { $regex: search, $options: "i" } },
                    { course: { $regex: search, $options: "i" } }
                ]
            };
        }

        const total = await Certificate.countDocuments(query);
        const certificates = await Certificate.find(query)
            .skip((page - 1) * limit)
            .limit(limit)
            .sort({ createdAt: -1 });

        const totalPages = Math.ceil(total / limit);

        res.json({ certificates, total, page, totalPages, limit });
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
};

const verifyCertificate = async (req, res) => {
    try {
        const cert = await Certificate.findOne({ certId: req.params.id });

        if (!cert) return res.json({ valid: false });

        res.json({ valid: true, cert });
    } catch (err) {
        res.status(500).json({ valid: false, message: "Error looking up certificate" });
    }
};

const downloadCertificate = async (req, res) => {
    let browser = null;
    try {
        const cert = await Certificate.findOne({ certId: req.params.id });
        if (!cert) return res.status(404).json({ message: "Certificate not found" });

        const templatePath = path.join(__dirname, '..', 'templates', 'certificate.html');
        let html = fs.readFileSync(templatePath, 'utf8');

        let qrCodeBase64 = cert.qrCode;
        if (!qrCodeBase64) {
            let frontendUrl = req.get('origin') || process.env.FRONTEND_URL || 'https://certiverify-eight.vercel.app';
            if (frontendUrl && frontendUrl.endsWith('/')) {
                frontendUrl = frontendUrl.slice(0, -1);
            }
            const verifyUrl = `${frontendUrl}/verify?id=${cert.certId}`;
            qrCodeBase64 = await qrcode.toDataURL(verifyUrl);
        }

        html = html.replace(/\{\{name\}\}/g, cert.name || 'Unknown');
        html = html.replace(/\{\{domain\}\}/g, cert.course || 'N/A');
        html = html.replace(/\{\{certificateId\}\}/g, cert.certId);
        html = html.replace(/\{\{date\}\}/g, cert.date || new Date().toISOString().split('T')[0]);
        html = html.replace(/\{\{qrCode\}\}/g, qrCodeBase64);

        browser = await puppeteer.launch({
            headless: true,
            executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || puppeteer.executablePath(),
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-gpu'
            ],
            timeout: 30000
        });

        const page = await browser.newPage();
        await page.setContent(html, { waitUntil: 'domcontentloaded', timeout: 20000 });

        const pdfBuffer = await page.pdf({
            width: '794px',
            height: '1123px',
            printBackground: true,
            margin: { top: 0, right: 0, bottom: 0, left: 0 }
        });

        await browser.close();
        browser = null;

        const filename = `${cert.certId}.pdf`;
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
        res.setHeader('Content-Length', pdfBuffer.length);
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Access-Control-Allow-Methods', 'GET');
        res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
        res.end(pdfBuffer);

    } catch (err) {
        console.error('PDF generation error:', err.message);
        if (browser) {
            try { await browser.close(); } catch (e) { console.error('Browser close error:', e.message); }
        }
        if (!res.headersSent) {
            res.status(500).json({ message: 'Failed to generate PDF: ' + err.message });
        } else {
            res.end();
        }
    }
};

module.exports = {
    uploadCertificates,
    createCertificate,
    getCertificates,
    verifyCertificate,
    downloadCertificate
};
